/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    alias(libs.plugins.android.app).apply(false)
    alias(libs.plugins.android.lib).apply(false)
    alias(libs.plugins.kotlin.android).apply(false)
}
